name: ezkart

services:
  gateway:
    build:
      context: ./backend/gateway
    container_name: ezkart-gateway
    restart: unless-stopped
    ports:
      - "5000:8080"                 # único puerto público de los servicios
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      ReverseProxy__Clusters__auth-cluster__Destinations__d1__Address: http://auth-api:8080/
    depends_on:
      - auth-api
    networks: [ezkart-net]

  auth-api:
    build:
      context: ./backend/services/auth
    container_name: ezkart-auth-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ConnectionStrings__Default: Host=auth-db;Port=5432;Database=auth_db;Username=${AUTH_DB_USER};Password=${AUTH_DB_PASSWORD}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
    depends_on:
      auth-db:
        condition: service_healthy
    networks: [ezkart-net]

networks:
  ezkart-net: